<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Base Link and Footprint Link-->

  <link name="base_link"></link>

  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="base_footprint"></link>

  <!-- Chassis Link -->

  <link name="chassis_link">
    <visual>
      <geometry>
        <mesh filename="${model_path}" scale="0.001 0.001 0.001"/>
      </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="blue">
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
      <!--origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/-->
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_box>
  </link>

  <joint name="chassis_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis_link"/>
    <origin xyz="0 0 ${initial_z_pose}"/>
  </joint>

  <!-- Right Front Wheel and Joint -->

  <link name="right_front_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black" />
    </visual>
    <collision>
      <geometry>
        <sphere radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <joint name="base_to_right_front_wheel" type="continuous">
    <parent link="base_link"/>
    <child link="right_front_wheel"/>
    <origin xyz="${wheel_front_offset_x} ${wheel_right_offset_y} ${wheel_all_offset_z}" rpy="-${pi/2} 0 0" />
    <axis xyz="0 0 1"/>
  </joint>

  <!-- Right Back Wheel and Joint -->

  <link name="right_back_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black" />
    </visual>
    <collision>
      <geometry>
        <sphere radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <joint name="base_to_right_back_wheel" type="continuous">
    <parent link="base_link"/>
    <child link="right_back_wheel"/>
    <origin xyz="${wheel_back_offset_x} ${wheel_right_offset_y} ${wheel_all_offset_z}" rpy="-${pi/2} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <!-- Left Front Wheel and Joint -->

  <link name="left_front_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black" />
    </visual>
    <collision>
      <geometry>
        <sphere radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <joint name="base_to_left_front_wheel" type="continuous">
    <parent link="base_link"/>
    <child link="left_front_wheel"/>
    <origin xyz="${wheel_front_offset_x} ${wheel_left_offset_y} ${wheel_all_offset_z}" rpy="-${pi/2} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <!-- Left Back Wheel and Joint -->

  <link name="left_back_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black" />
    </visual>
    <collision>
      <geometry>
        <sphere radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <joint name="base_to_left_back_wheel" type="continuous">
    <parent link="base_link"/>
    <child link="left_back_wheel"/>
    <origin xyz="${wheel_back_offset_x} ${wheel_left_offset_y} ${wheel_all_offset_z}" rpy="-${pi/2} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

</robot>
    