# Basic dimensions of Laika robot

base:
  length: 0.29
  width: 0.12
  depth: 0.1
  mass: 1.7
  mesh: "box.dae"

wheel:
  width: 0.04
  radius: 0.05
  mass: 0.05
  mesh: "box.dae"

camera:
  length: 0.025
  width: 0.03
  depth: 0.03
  mass: 0.01
  rad_lens: 0.0025
  len_lens: 1.003
  mesh: "box.dae"

lidar:
  radius: 0.03
  length: 0.07
  mass: 0.1
  filename: "box.dae"
